// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

// 账户表
type Account struct {
	ID    int64  `json:"id"`
	Owner string `json:"owner"`
	// 余额
	Balance int64 `json:"balance"`
	// 货币名称
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

// 流水表
type Entry struct {
	ID int64 `json:"id"`
	// 对应的账户
	AccountID int64 `json:"account_id"`
	// 金额，正表示转入，负表示转出
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

// 转帐表
type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// 转账金额，一定要为正
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
